name = "cv-stats"
main = "cv-stats-worker.js"
compatibility_date = "2026-01-01"
account_id = "7c8e92f537fc4bcc1056ef12e6b70669"

[[kv_namespaces]]
binding = "CV_STATS"
id = "f9f3464f85d14b64abdb885d87254b91"
